import { Button, TextEdit, TabWidget } from "std-widgets.slint";
import { DropdownMenu } from "dropdown-menu.slint";

export global Palette {
    in-out property <color> dark-purple: #1B2430;
    in-out property <color> primary: #51557E;
    in-out property <color> secondary: #816797;
    in-out property <color> dark-secondary: #392a45;
    in-out property <color> tertiary: #D6D5A8;
    in-out property <color> white: #FFF2F9;
    in-out property <color> black: #323232;
    in-out property <color> dropwdown: #d9d9d9;
}

component Main inherits Window {
    width: 1280px;
    height: 720px;

    MenuBar {
        
    }

    VerticalLayout {
        HorizontalLayout {
            

            max-height: 200px;
            DropdownMenu {
                background: Palette.tertiary;
                dropdownBackground: Palette.dropwdown;
                options: ["Test", "Testing"];
            }
        }

        HorizontalLayout {
            TextEdit {
                font-size: 14px;
                width: parent.width / 2;
                text: "Hi!";
            }

            TabWidget {
                Tab {
                    title: "Lexico";
                }

                Tab {
                    title: "Sintactico";
                }

                Tab {
                    title: "Semantic";
                }

                Tab {
                    title: "Intermidiate code";
                }

                Tab {
                    title: "Execution";
                }
            }
        }

        Rectangle {
            max-height: 30px;
            background: Palette.secondary;
            Text {
                text: "Errors";
                horizontal-alignment: left;
                color: Palette.white;
                font-size: 20px;
            }
        }

        Rectangle {
            max-height: 150px;
            background: Palette.primary;
        }

        Rectangle {
            max-height: 30px;
            background: Palette.tertiary;
        }
    }
}

export component IDE inherits Window {
    width: 1280px;
    height: 720px;
    Main { }
}
